{% set version = "1.5.0" %}

package:
  name: geoviews
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoviews/geoviews-{{ version }}.zip
  sha256: e904010fc8517f23fd9faaa6a8957c1626e78f1447494d193d80547c837d3cba

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - geoviews = geoviews.__main__:main

requirements:
  host:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.6.1,<2.0
    - numpy >=1.0
    - holoviews >=1.10.1
    - cartopy >=0.14.2
    # extras
    - jupyter
    - notebook
    - bokeh >=0.12.13

test:
  imports:
    - geoviews

about:
  home: http://geoviews.org
  license: BSD 3-Clause
  license_family: BSD
  # license is not packages in the source tarball :-(
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Simple, concise geographical visualization in Python
  description: |
    GeoViews is a Python library that makes it easy to explore and visualize
    geographical locations. It has particularly powerful support for
    multidimensional meteorological and oceanographic datasets, such as those
    used in weather, climate, and remote sensing research, but is useful for
    almost anything that you would want to plot on a map!
  dev_url: https://github.com/ioam/geoviews
  doc_url: http://geoviews.org/user_guide/index.html

extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
