{% set name = "geoviews" %}
{% set version = "1.15.1" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c72097ef4f24895c46f95834e5c19ac185ea1c34fd610f0f956421ba515d4aad

build:
  number: 0
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-vcs
    - bokeh ==3.8.*

outputs:
  - name: geoviews-core
    script: build_base.sh  # [not win]
    script: build_base.bat  # [win]
    build:
      skip: true  # [py<310]
      entry_points:
        - geoviews = geoviews.command:main
    requirements:
      run_constrained:
        - geoviews {{ version }}
      host:
        - python
        - pip
        - nodejs >=20
        - hatchling
        - hatch-vcs
        - bokeh ==3.8.*
      run:
        - python
        - bokeh >=3.8.0
        - cartopy >=0.18.0
        - holoviews >=1.16.0
        - numpy
        - packaging
        - panel >=1.0.0
        - param >=1.9.3,<3.0
        - pyproj
        - shapely >=1.8.0
        - xyzservices
    test:
      commands:
        - pip check
      imports:
        - geoviews
      requires:
        - pip

  - name: geoviews
    build:
      skip: true  # [py<310]
    requirements:
      host:
        - python
        - pip
        - hatchling
        - hatch-vcs
        - bokeh ==3.8.*
      run:
        - python
        - {{ pin_subpackage('geoviews-core', exact=True) }}
        - datashader
        - geopandas-base
        - netcdf4
        - pandas
        - pyct
        - xarray
        - scipy
        - pooch
        - matplotlib-base >2.2
    test:
      imports:
        - geoviews
      commands:
        - pip check
      requires:
        - pip
    about:
      home: https://geoviews.org
      license: BSD-3-Clause
      license_family: BSD
      license_file: LICENSE
      summary: GeoViews is a Python library that makes it easy to explore and visualize geographical, meteorological, and oceanographic datasets, such as those used in weather, climate, and remote sensing research.
      description: |
        GeoViews is built on the HoloViews library for building flexible visualizations of multidimensional data.
        GeoViews adds a family of geographic plot types based on the Cartopy library,
        plotted using either the Matplotlib or Bokeh packages.
      doc_url: https://geoviews.org
      dev_url: https://github.com/holoviz/geoviews

about:
  home: https://geoviews.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: GeoViews is a Python library that makes it easy to explore and visualize geographical, meteorological, and oceanographic datasets, such as those used in weather, climate, and remote sensing research.
  description: |
    GeoViews is built on the HoloViews library for building flexible visualizations of multidimensional data.
    GeoViews adds a family of geographic plot types based on the Cartopy library,
    plotted using either the Matplotlib or Bokeh packages.
  doc_url: https://geoviews.org
  dev_url: https://github.com/holoviz/geoviews

extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
    - maximlt
    - Hoxbro
    - ahuang11
  skip-lints:
    - host_section_needs_exact_pinnings
