{% set version = "1.5.0" %}

package:
  name: geoviews
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/geoviews/geoviews-{{ version }}.zip
  sha256: e904010fc8517f23fd9faaa6a8957c1626e78f1447494d193d80547c837d3cba

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python
    - param >=1.6.1,<2.0
    - numpy >=1.0
    - holoviews >=1.10.0
    - cartopy >=0.14.2
    # extras
    - jupyter
    - notebook
    - bokeh >=0.12.15

test:
  imports:
    - geoviews

about:
  home: http://geoviews.org
  license: BSD 3-Clause
  # license_file: LICENSE  # license is not packages in the source tarball :-(
  summary: 'GeoViews is a Python library that makes it easy to explore and visualize geographical'

extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
