{% set version = "1.5.1" %}

package:
  name: geoviews
  version: {{ version }}

build:
  number: 0
  noarch: python

requirements:
  host:
    - python
    - pip
    - param >=1.6.1,<2.0
  run:
    - python >=2.7
    - datashader
    - gdal
    - geopandas
    - geoviews-core ={{ version }}
    - jupyter
    - libgdal
    - matplotlib
    - netcdf4 <1.4.0
    - pandas
    - pyct
    - scipy
    - shapely
    - xarray

test:
  imports:
    - geoviews
  requires:
    - nbsmoke
    - pytest
  commands:
    - geoviews examples --path=. --force
    # just run one notebook for now; increase in the future if notebooks can be run quickly with test/tiny data
    - pytest --nbsmoke-run -k ".ipynb" user_guide/Geometries.ipynb

about:
  home: http://geoviews.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Simple, concise geographical visualization in Python
  description: |
    GeoViews is a Python library that makes it easy to explore and visualize
    geographical locations. It has particularly powerful support for
    multidimensional meteorological and oceanographic datasets, such as those
    used in weather, climate, and remote sensing research, but is useful for
    almost anything that you would want to plot on a map!
  dev_url: https://github.com/ioam/geoviews
  doc_url: http://geoviews.org/user_guide/index.html

extra:
  recipe-maintainers:
    - ocefpaf
    - philippjfr
