travis:
  secure:
    BINSTAR_TOKEN: Jv+L1487mFN7cw9WxVesCgKaDEyZ2iKNI3Nb1Mj+W6D2pU8i5bv9uBwnQjNQI4V/NKorhO0DAFyCDdRtn3fL0h1mbquTWKVbtiiPWY94evKB72nde6INvvtTQxzitX755YfYAf+L62nQx6iyO0qsqDAz10Z3Orn/HD/2KuIvJUQyYpB3ziUKYMMqi+YLPCTLVuch/fCzepYpSSMJzMNkFe5/v55ru1hVf18V0Oi0N7vFtbo0L6Ow1S6tyZFFysvn8dsnXxTBILPFoPWJ9mpmTlev8Po2j+LuemcEEulRimDqPpRyPK3ztjJV+3a0/wAhJSMyHQ3no6wNX0Ks3NomFPFCb87/hURBzKyivy2KLBia3jX6rsqYhw89L9dUwjd7La5wqThPUFen41VdTjIeOELuIRhsPDcJlb+isBqYao3CsJRBg6bo9lEPsqZrneDNZKxkXhajPJMtcnJBp+aaHmk1f7t0ftpeUCx0qOMeM9mdx/0sPWqzJv/d9ZG7QUJf/H4JtpyR01lm+csvfRarslEsEXLNMob7tW3oKZpDNq5/WpDkjSiXkaa1UqKcPVaHFjYtg2khX+bzA4NtHUfRaUgkgx44ffJ1/1UISSi3NzX1f1sEJLClh59iq/q+2WRXBuOOfz54N4Z6nqJ8tDdncGKX4I9TSsk03naOL2QCbEE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
