travis:
  secure:
    BINSTAR_TOKEN: AqCB66xrK9SKhR53OkE+Pzr8iyghwRLr6HU2o2SucpXq9LozwSmzXf1Lu8VTh1dMcSUUS87auDifmuFd6gphx6BSOMqFwW7DeK73WUyHyxA9fwISqKHaCd/IpY/R4Us1/RFJULmCIuxhtUuCciG0qeDYx7ThQ4AqXIKRwOhCRhIIe7pTzXM8ILAAMuzNEE5GDLPa2Hct95ipJEVukfkL6Q1Ipz6MvYVIalWCfECYaqNijMZhkCgjW1EfkybcP/QRiTGoGGkyItpWh4zXpvqkkzQUpQUepk/yEeIqo/h2ghp3HMwX6m94aVcpmJu4IMXdpbqicl0ZEvAumBMLM4GdK0SGx2BWg/VpM0WPyRCE3NY/cf0lEePw60etIuXfakDOsIQ50N8RrFydASbvUXm3UKgGRSrklybOQPzHgFzJJWL0BsAF7AaoXl7BRNPfL3pNrk+dsqqQ5S63EsCLbHubeojYmMr35nIkSdlmkHNtJa06EiOeEJQ8t8R/JcQ4B8mvoY+vq7veg1vtuNKZGT6B2IjxgwOVE7WGHM8ptdHm78s84oOv/ezJEqxSOwXW01qrXRsSdamOKbvIgPbrF6VJPbFFDsuiFd0GiXV4ofTstM8B9CogOkUtF5VBvFgH86Fhx20bN4BUv15zyXwsF6cmUEVZvDi3MfIOj09anh1P5yk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
